const mongoose = require("./mongoose");
const auction = require("./auction.model");
const province = require("./province.model");
const db = {};
db.mongoose = mongoose;
db.auction = auction;
db.province = province;
db.address = mongoose.db.collection("laos-address");
module.exports = db;
